version: '3'

vars:
  BINARY_NAME: transfer-service
  DOCKER_IMAGE: transfer-service

tasks:
  clean:
    desc: Clean build artifacts
    cmds:
      - go clean
      - rm -f {{.BINARY_NAME}}

  build:
    desc: Build the application with debugging symbols
    deps: [format]
    cmds:
      - go mod tidy
      - CGO_ENABLED=0 GOOS=linux go build -gcflags="all=-N -l" -o {{.BINARY_NAME}} ./cmd/...

  attach-debugger:
    desc: Attach debugger to the running container
    cmds:
      - dlv exec ./{{.BINARY_NAME}} --headless --listen=:2345 --api-version=2 --accept-multiclient

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  itest:
    desc: Run only the integration test
    cmds:
      - go test -v ./integration_test.go

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  format:
    desc: Format Go code
    cmds:
      - gofmt -w .
      - goimports -w .

  docker:
    desc: Build Docker image
    deps: [build]
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .

  run:
    desc: Run the application
    cmds:
      - ./{{.BINARY_NAME}}

  dev:
    desc: Run the application in development mode
    cmds:
      - go run main.go

  up:
    desc: Start the application and database using Docker Compose
    cmds:
      - docker compose up -d

  down:
    desc: Stop and remove the Docker Compose services
    cmds:
      - docker compose down

  deploy:
    desc: Rebuild and deploy the application 
    cmds:
      - task: docker
      - task: up

  default:
    desc: Default task - clean, format, build, test, and create Docker image
    deps: [clean, build, test, docker] 